security:
    encoders:
        "FOS\UserBundle\Model\UserInterface": sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: /sprawdz_logowanie/
                login_path: /logowanie/
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                path:   /wylogowanie/
                target: /

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - {path: ^/druzyna/.+/edytuj, roles: ROLE_USER}
        - {path: ^/druzyna/.+/nowa_akcja, roles: ROLE_USER}
        - {path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
